# Site settings
title: امدادنا
email: info@emdadna.com
description: امدادنا - راهکارهای مقابله و مواجهه با بلایای طبیعی
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: emdadna
github_username:  faroxa

# Build settings
markdown: kramdown
